### ISSUE TITLE
Need more documentation Google Play 

### ISSUE THREAD

**Issue by Warmachine13** [SudoPlz/sp-react-native-in-app-updates#29]
Need add to README steps of configuration of google play like 

- add com.google.android.play:core
- Enffort REAL DEVICE with SAME ACCOUNT EMAIL
- Have one app on google play with same name of yours and same account
- Enable Internal app sharing on the google play 
- add Testers email in internal testing 
- call function installUpdate on status 11 of progress

**Comment by SudoPlz** [comment]
Those are mostly generic instructions about setting up in-app-updates using play core services, and there are plenty of tutorials and instructions on the web.
The purpose of this library is only to expose that functionality to react-native apps (and not teach developers how to use the play core framework).

That being said, those extra instructions on our Readme would be more than welcome and would probably help developers further down the line, so feel free to open a PR if you feel like contributing.

Even better, we even could provide external documentation urls - probably from google docs or stack overflow- (so that we don't re-invent the wheel with yet another tutorial of ours - and that way it won't get outdated as play core docs change).

Both of the above would be perfectly fine.

**Comment by invyctus92** [comment]
Hi, I am interested in adding this functionality to my app but am having several difficulties. Could someone help me to correctly configure the library and use it in different cases, especially android. Thanks

**Comment by divyasri93** [comment]
I've followed the steps and finally while debugging using the link from internal app sharing, its redirected to playstore with my app opened but **Install** button is missing in it! My app is supported only in US. I'm trying from a different country. Could that be the reason? Kindly clarify, Thanks.

**Comment by SudoPlz** [comment]
@divyasri93 I'm afraid I don't have an answer to that.
Your question is a generic android in-app-updates question and would be better answered in stackoverflow.
