### ISSUE TITLE
Not working with Expo

### ISSUE THREAD

**Issue by rahul-budhia** [SudoPlz/sp-react-native-in-app-updates#3]
Hi, I am trying to use this in my expo app. I am assuming native linking doesn't work for it right now with expo. I get the following error. Is there any plan to make it work with expo? \
\
![inappupdate](https://user-images.githubusercontent.com/8077032/88384899-93260480-cdad-11ea-9195-ad269d9154c4.jpeg)

Thanks

**Comment by SudoPlz** [comment]
Hey there @rahul-budhia - we're not using expo at all, but if the project is exported it should work since it's just another react-native project.

I'm not super familiar with expo myself, but a PR would be super welcome!

**Comment by Gustash** [comment]
@rahul-budhia Expo only works with native packages that Expo themselves bundle in, you might have some luck with ExpoKit, but I've personally never tried it.

**Comment by a-eid** [comment]
@gustash that is not the case anymore with expo custom dev clients and expo plugins.
you can create a plugin for any native package to work with an expo custom dev client.

**Comment by devakrishna33** [comment]
You can build a dev client but because of it's dependency to react native device info it'll throw an error stating react native device info is not defined. 

Inorder to make this work you can try the following,

In babel.config.js add an alias to react native device info,
```
const config = {
  plugins: [
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        root: ['.'],
        alias: {
          // Add this line
          "react-native-device-info": "./react-native-device-info.js"
        },
      },
    ],
  ],
}
```

And in react-native-device-info.js add this
```
import Constants from "expo-constants"

export const getVersion = () => {
    return Constants.expoConfig?.version
}
```

This will replace the getVersion function from react-native-device-info. Make sure to restart the expo server with "--clear".

**Comment by SudoPlz** [comment]
@devakrishna33 thank you for this workaround, I wasn't aware of it.

@krisgerhard feel free to open a PR, with a link to this solution, and I'll be happy to approve.
